version: "2"

linters:
  default: standard
  enable:
    - cyclop
    - gocritic
    - gosec
    - ineffassign
    - misspell
    - prealloc
    - unconvert
    - unparam
    - whitespace
    - asciicheck
    - bodyclose
    - dupl
    - govet
    - goconst
    - misspell
    - staticcheck
  settings:
    cyclop:
      max-complexity: 25

formatters:
  enable:
    - gofumpt
    - goimports
    - golines
  settings:
    golines:
      max-len: 120