name: Test
on:
  pull_request:
    branches: [ 'main' ]
  push:
    branches: [ 'main' ]
jobs:
  lint:
    name: Run linters
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: './go.mod'
      - name: Run linters
        uses: golangci/golangci-lint-action@v8
        with:
          args: --verbose
  test:
    name: Run tests
    runs-on: ubuntu-22.04
    needs: lint
    strategy:
      matrix:
        go: [ '1.23', 'latest' ]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}

      - name: Install dependencies
        run: go mod download

      - name: Run tests
        run: go test -v -timeout 10m -race -covermode atomic -coverprofile=coverage.out -coverpkg=github.com/xsqrty/op/... ./...

      - name: Display total coverage
        run: echo Total coverage $(go tool cover -func=coverage.out | tail -n 1 | awk '{print $3}')

      - name: Upload coverage artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage-${{ matrix.go }}
          path: coverage.out

  coverage-upload:
    name: Upload coverage
    runs-on: ubuntu-22.04
    needs: test
    steps:
      - name: Download coverage artifact
        uses: actions/download-artifact@v4
        with:
          name: coverage-latest

      - name: Upload coverage
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: coverage.out